language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github_token: $github_token
  local-dir: build
  on: 
    branch: master